/*
 *
 *  This file is part of the XForms library package.
 *
 * XForms is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1, or
 * (at your option) any later version.
 *
 * XForms is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with XForms; see the file COPYING.  If not, write to
 * the Free Software Foundation, 59 Temple Place - Suite 330, Boston,
 * MA 02111-1307, USA.
 *
 */


/* Header file generated by fdesign on Tue Nov  5 18:02:58 2013 */

#ifndef FD_form_h_
#define FD_form_h_

#include "include/forms.h"

/* Callbacks, globals and object handlers */

extern void clear_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * form;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * input;
    FL_OBJECT * cancel;
    FL_OBJECT * ok;
} FD_form;

extern FD_form * create_form_form( void );

#endif /* FD_form_h_ */
