/** Header file generated by fdesign on Wed May  7 22:23:18 2008.**/

#ifndef FD_buttonattrib_h_
#define FD_buttonattrib_h_

/** Callbacks, globals and object handlers **/

extern void initialval_change( FL_OBJECT *, long );
extern void iconbutton_filename_change( FL_OBJECT *, long );
extern void pixalign_change( FL_OBJECT *, long );
extern void showfocus_change( FL_OBJECT *, long );
extern void lookfor_pixmapfile_cb( FL_OBJECT *, long );
extern void usedata_change( FL_OBJECT *, long );
extern void fullpath_cb( FL_OBJECT *, long );
extern void focusiconbutton_filename_change( FL_OBJECT *, long );
extern void helper_change_cb( FL_OBJECT *, long );
extern void react_to_button( FL_OBJECT *, long );


/**** Forms and Objects ****/

typedef struct {
    FL_FORM   * buttonattrib;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * background;
    FL_OBJECT * initialval;
    FL_OBJECT * filename;
    FL_OBJECT * pixalign;
    FL_OBJECT * showfocus;
    FL_OBJECT * browse;
    FL_OBJECT * use_data;
    FL_OBJECT * fullpath;
    FL_OBJECT * focus_filename;
    FL_OBJECT * browse2;
    FL_OBJECT * tooltip;
    FL_OBJECT * mbuttons_label;
    FL_OBJECT * react_left;
    FL_OBJECT * react_middle;
    FL_OBJECT * react_right;
    FL_OBJECT * react_up;
    FL_OBJECT * react_down;
} FD_buttonattrib;

extern FD_buttonattrib * create_form_buttonattrib( void );

#endif /* FD_buttonattrib_h_ */
