/** Header file generated by fdesign on Wed May  7 22:23:18 2008.**/

#ifndef FD_menuattrib_h_
#define FD_menuattrib_h_

/** Callbacks, globals and object handlers **/

extern void add_menu_item_cb( FL_OBJECT *, long );
extern void delete_menu_item_cb( FL_OBJECT *, long );
extern void change_menu_item_cb( FL_OBJECT *, long );
extern void clear_menu_field_cb( FL_OBJECT *, long );
extern void replace_menu_item_cb( FL_OBJECT *, long );
extern void new_menuapi_cb( FL_OBJECT *, long );
extern void menuentry_scope_cb( FL_OBJECT *, long );


/**** Forms and Objects ****/

typedef struct {
    FL_FORM   * menuattrib;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * content_br;
    FL_OBJECT * input;
    FL_OBJECT * auto_clear;
    FL_OBJECT * mode;
    FL_OBJECT * shortcut;
    FL_OBJECT * new_menuapi;
    FL_OBJECT * scope;
} FD_menuattrib;

extern FD_menuattrib * create_form_menuattrib( void );

#endif /* FD_menuattrib_h_ */
