/* Header file generated by fdesign on Thu Nov  7 21:58:33 2013 */

#ifndef FD_twheelattrib_h_
#define FD_twheelattrib_h_

#include <forms.h>

/* Callbacks, globals and object handlers */

extern void twheel_minmax_change( FL_OBJECT *, long );
extern void twheel_returnsetting_change( FL_OBJECT *, long );
extern void twheel_initialvalue_change( FL_OBJECT *, long );
extern void twheel_step_change( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * twheelattrib;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * background;
    FL_OBJECT * minval;
    FL_OBJECT * maxval;
    FL_OBJECT * returnsetting;
    FL_OBJECT * initial_val;
    FL_OBJECT * step;
} FD_twheelattrib;

extern FD_twheelattrib * create_form_twheelattrib( void );

#endif /* FD_twheelattrib_h_ */
