/* Form definition file generated by fdesign. */

#include "include/forms.h"
#include <stdlib.h>
#include "ui_objs.h"



/***************************************
 ***************************************/

FD_buttonform *
create_form_buttonform( void )
{
    FL_OBJECT *obj;
    FD_buttonform *fdui = fl_malloc( sizeof *fdui );



    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->buttonform = fl_bgn_form( FL_NO_BOX, 581, 51 );

    obj = fl_add_box( FL_NO_BOX, 0, 0, 581, 51, "" );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 581, 51, "" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 20, 3, 30, 30, "button" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 60, 3, 30, 30, "round" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 100, 3, 30, 30, "round3d" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 140, 3, 30, 30, "check" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 180, 3, 30, 30, "light" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 220, 3, 30, 30, "bitmap" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 260, 3, 30, 30, "pixmap" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 300, 3, 30, 30, "scroll" );
    fl_end_form( );

    fdui->buttonform->fdui = fdui;

    return fdui;
}


/***************************************
 ***************************************/

FD_valuatorform *
create_form_valuatorform( void )
{
    FL_OBJECT *obj;
    FD_valuatorform *fdui = fl_malloc( sizeof *fdui );



    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->valuatorform = fl_bgn_form( FL_NO_BOX, 581, 51 );

    obj = fl_add_box( FL_NO_BOX, 0, 0, 581, 51, "" );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 581, 51, "" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 20, 5, 30, 30, "slider" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 66, 5, 30, 30, "valslider" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 112, 5, 30, 30, "scrollbar" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 158, 5, 30, 30, "dial" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 204, 5, 30, 30, "counter" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 250, 5, 30, 30, "positioner" );
    fl_end_form( );

    fdui->valuatorform->fdui = fdui;

    return fdui;
}


/***************************************
 ***************************************/

FD_staticform *
create_form_staticform( void )
{
    FL_OBJECT *obj;
    FD_staticform *fdui = fl_malloc( sizeof *fdui );



    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->staticform = fl_bgn_form( FL_NO_BOX, 581, 51 );

    obj = fl_add_box( FL_NO_BOX, 0, 0, 581, 51, "" );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 581, 51, "" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 20, 3, 30, 30, "box" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 70, 3, 30, 30, "frame" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 120, 3, 30, 30, "labelframe" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 170, 3, 30, 30, "text" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 220, 3, 30, 30, "bitmap" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 270, 3, 30, 30, "pixmap" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 320, 3, 30, 30, "chart" );

    obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 370, 3, 30, 30, "clock" );
    fl_end_form( );

    fdui->staticform->fdui = fdui;

    return fdui;
}
